spring.application.name=Nutricode

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/nutricode
spring.datasource.username=seu_usuario
spring.datasource.password=sua_senha
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#TokenJWT
api.security.token.secret=${JWT_SECRET}

#App
app.base-url=${BASE_URL}

# Admin Seed
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.username=${ADMIN_USERNAME}

#Swagger, melhorar leitura
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha